# tb3_8_nav2_params.yaml
amcl:
  ros__parameters:
    use_sim_time: true
    laser_min_range: 0.12
    laser_max_range: 3.5
    laser_model_type: "likelihood_field"
    min_particles: 500
    max_particles: 2000

# map_server:
#   ros__parameters:
#     use_sim_time: true
#     yaml_filename: /path/to/your/map.yaml
#     frame_id: "map"

planner_server:
  ros__parameters:
    use_sim_time: true
    expected_planner_frequency: 20.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"

controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 20.0

    # Controller plugins
    controller_plugins: ["FollowPath"]

    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: false

      # Velocity constraints
      min_vel_x: 0.0
      max_vel_x: 0.26
      min_vel_y: 0.0
      max_vel_y: 0.0
      min_speed_theta: 0.0
      max_speed_theta: 1.82
      acc_lim_x: 2.5
      acc_lim_y: 0.0
      acc_lim_theta: 3.2
      decel_lim_x: -2.5
      decel_lim_y: 0.0
      decel_lim_theta: -3.2

      # Critics to evaluate trajectories
      critics: 
        - RotateToGoal
        - Oscillation
        - ObstacleFootprint
        - PathAlign
        - GoalAlign
        - GoalDist

      RotateToGoal:
        scale: 1.0

      Oscillation:
        scale: 1.0

      ObstacleFootprint:
        scale: 10.0

      PathAlign:
        scale: 32.0

      GoalAlign:
        scale: 24.0

      GoalDist:
        scale: 20.0




bt_navigator:
  ros__parameters:
    use_sim_time: true

waypoint_follower:
  ros__parameters:
    use_sim_time: true
